spring.datasource.url=jdbc:postgresql://dpg-d7lnpb68bjmc73agibrg-a.virginia-postgres.render.com:5432/kot_db
spring.datasource.username=kotuser
spring.datasource.password=uwZ3l81FyTua0MLdHZtMOjmkHUrC4jl2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=10000